W7/W7D3/capybara/Music_App/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :new, :show, :create]
  resources :bands
  resource :session, only: [:new, :create, :destroy]
end

W7/W7D3/capybara/Music_App/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  
end

W7/W7D3/capybara/Music_App/app/models/user.rb
class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email,password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end


end

W7/W7D3/capybara/Music_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def required_login
    redirect_to new_session_url unless current_user
  end

  def required_logout
    redirect_to bands_url if logged_in?
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def logged_in?
    !!current_user
  end
end

W7/W7D3/capybara/Music_App/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def show
    @bands = Band.find_by(params[:id])
    render :show
  end

    
end

W7/W7D3/capybara/Music_App/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  before_action :required_logout, only: [:new, :create]
  before_action :required_login, only: [:destroy]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      # render json: ["invalid credentials"], status: 401
      flash.now[:errors] = ['Invalid Username or Password']
      render :new
    end
  end
  
  def destroy
    logout!
    redirect_to new_session_url
  end


end

W7/W7D3/capybara/Music_App/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :required_logout, only: [:new, :create]
  before_action :required_login, only: [:index, :show]

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def new 
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to bands_url
    else 
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W7/W7D3/capybara/Music_App/app/helpers/bands_helper.rb
module BandsHelper
end

W7/W7D3/capybara/Music_App/app/views/bands/index.html.erb
<h2>BANDS</h2>
<ul>
<% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
  <% end %>
</ul>

<br>
<br>
<br>
<h4>LINKS</h4>
<br>
<a href="<%= new_band_url %>">New band</a>

W7/W7D3/capybara/Music_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  <header>
  <h1>MUSIC APP</h1>
<% if logged_in? %>
    <form action="<%= bands_url %>" method="get">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <input type="submit" value="Take me Home">
    </form>
    <h3>logged in as:<%=current_user.email%></h3>
    </form>
  <form action="<%= session_url %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Sign Out">
    </form>
  <% end %>
  </header>
    <%= yield %>
  </body>
</html>

W7/W7D3/capybara/Music_App/app/views/users/new.html.erb
<h2>NEW USER</h2>
<form action ="<%=new_session_url%>" method="GET">
<input type="submit" value="Go to Sign-in!">
</form>
<form action="<%=users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>

  <label>Email:
  <input type="text" name="user[email]" value="<%= @user.email %>">
  </label>

  <br>

  <label>Password:
  <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Submit">


</form>